package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"fmt"
)

// Dummy is the resolver for the dummy field.
func (r *mutationResolver) Dummy(ctx context.Context, b bool) (bool, error) {
	panic(fmt.Errorf("not implemented: Dummy - dummy"))
}

// Dummy is the resolver for the dummy field.
func (r *queryResolver) Dummy(ctx context.Context, b bool) (bool, error) {
	panic(fmt.Errorf("not implemented: Dummy - dummy"))
}

// Retrieve is the resolver for the retrieve field.
func (r *queryResolver) Retrieve(ctx context.Context, search string, from int, size int) (string, error) {
	return sender.Retrieve(search, int32(from), int32(size))
}

// Aggregate is the resolver for the aggregate field.
func (r *queryResolver) Aggregate(ctx context.Context) (string, error) {
	return sender.Aggregate()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
