// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggregationCategory struct {
	DocCount int    `json:"DocCount"`
	Key      string `json:"Key"`
}

type Data struct {
	ID          string  `json:"Id"`
	Subcategory string  `json:"Subcategory"`
	TitleRo     string  `json:"TitleRo"`
	TitleRu     string  `json:"TitleRu"`
	Type        string  `json:"Type"`
	Posted      float64 `json:"Posted"`
}

type Mutation struct {
}

type Query struct {
}
